const profile={
name:'Jonatan Alexander Cotacio Caicedo',
role:'Senior Backend Engineer · Tech Lead hands-on',
headline:'Construyo backend estable y lidero la evolución de sistemas <em>preparados para crecer.</em>',
summary:'Diseño APIs, microservicios y arquitecturas distribuidas, combinando desarrollo hands-on, liderazgo técnico, uso directo de AWS en proyectos independientes y colaboración con equipos DevOps.',
highlights:['Más de 9 años de experiencia','Migración de monolito a microservicios','55 % menos tiempo de respuesta','Liderazgo técnico hands-on'],
featuredSkills:['Node.js','NestJS','Spring Boot','AWS','Microservicios','PostgreSQL'],
cloud:{awsLevel:'Uso directo en proyectos independientes y participación con DevOps en entornos empresariales',directServices:['S3','CloudWatch','DynamoDB','ElastiCache','Terraform'],supportServices:['EC2','Lambda','ECS','EKS','RDS','Aurora','API Gateway','SNS'],laboratories:['VPC','ALB','Secrets Manager'],knowledge:['CloudFront','Route 53','IAM','WAF','Auto Scaling']}
};
const specialties=[
['⌁','Liderazgo técnico','Acompañamiento a equipos mediante revisión de código, definición de criterios técnicos, resolución de bloqueos y apoyo en decisiones de arquitectura.'],
['↔','Diseño de APIs y servicios backend','Construcción de servicios REST escalables, seguros y orientados a rendimiento y mantenibilidad.'],
['◇','Arquitectura y evolución de sistemas','Diseño y migración de sistemas hacia arquitecturas más escalables, desacopladas y resilientes.'],
['ƒ','Lógica de negocio','Implementación de procesos backend alineados con necesidades funcionales, técnicas y operativas.'],
['▱','Bases de datos','Modelado, integración y optimización de bases de datos relacionales y NoSQL en entornos productivos.'],
['⇢','Procesamiento asíncrono y mensajería','Construcción de flujos desacoplados y procesamiento en segundo plano mediante sistemas de mensajería.'],
['⌾','Seguridad','Implementación de autenticación, autorización y prácticas basadas en OAuth 2.0, Auth0, JWT, JWE y OWASP.'],
['△','DevOps y despliegue','Apoyo en contenerización, despliegue y automatización mediante Docker, Kubernetes y procesos CI/CD.']];
const tech={Backend:['Express','PHP','Laravel','Lumen','CodeIgniter','Yii 2.0'],Frontend:['Angular','AngularJS','Vue.js','JavaScript','HTML5','CSS'],'Bases de datos':['Oracle','MySQL'],'AWS — uso directo':['S3','CloudWatch','DynamoDB','ElastiCache','Terraform'],'AWS — participación con DevOps':['EC2','Lambda','ECS','EKS','RDS','Aurora','API Gateway','SNS'],'AWS — laboratorios':['VPC','ALB','Secrets Manager'],'AWS — conocimientos':['CloudFront','Route 53','IAM','WAF','Auto Scaling'],'Mensajería e integración':['RabbitMQ','Kafka','NATS','APIs REST','SOAP'],Seguridad:['OAuth 2.0','Auth0','JWT','JWE','OWASP'],'DevOps y calidad':['Jenkins','GitLab CI/CD','GitHub Actions','SonarQube','Git'],Arquitectura:['Microservicios','Sistemas distribuidos','Clean Architecture','CQRS','Saga','SOLID','Arquitectura orientada a eventos']};
const workPractices=[
{name:'Descubrimiento',description:'Análisis de requerimientos, refinamiento y estimación técnica.'},
{name:'Diseño',description:'Diseño de APIs, modelado de datos y elaboración de diagramas.'},
{name:'Construcción',description:'Desarrollo hands-on, pair programming, pruebas unitarias y de integración.'},
{name:'Calidad',description:'Revisión de código, CI/CD, seguridad y documentación técnica.'},
{name:'Operación',description:'Observabilidad, análisis de logs y manejo de incidentes en producción.'},
{name:'Liderazgo',description:'Mentoring, coordinación técnica y resolución de bloqueos.'}
];
const jobs=[
{role:'Líder Técnico',company:'Periferia IT',period:'Oct 2023 — Mar 2026',points:['Liderazgo de la migración de una arquitectura monolítica hacia microservicios.','Diseño e implementación de servicios backend con NestJS y Express.','Coordinación del equipo y decisiones de arquitectura, mensajería, datos, seguridad y rendimiento.'],tech:'NestJS · Express · Redis · PostgreSQL · MongoDB · RabbitMQ · OAuth 2.0 · Docker · Kubernetes',achievement:'Coordinación e implementación con el equipo de nuevos flujos autogestionados, reduciendo un 55 % los tiempos de respuesta y un 85 % la contactabilidad al call center.'},
{role:'Solution Consultant II',company:'Sophos Solutions',period:'Ago 2021 — Jul 2023',points:['Participación en tres proyectos de alta complejidad para banca y retail.','Desarrollo y evolución de más de 20 APIs REST y aplicaciones empresariales.','Referente técnico transversal y coordinación de dos desarrolladores backend.'],tech:'Spring Boot · NestJS · Node.js · Angular · Vue.js · Oracle · PostgreSQL · Auth0 · Docker',achievement:'Más de 20 APIs REST desarrolladas o evolucionadas y coordinación directa de 2 desarrolladores backend.'},
{role:'Consultor IT',company:'Rawson BPO',period:'May 2021 — Jul 2021',points:['Desarrollo y mantenimiento de una plataforma de control y monitoreo de trenes.','Nuevas vistas, mejoras de usabilidad y corrección de errores.','Soporte a integraciones backend en producción.'],tech:'Vue.js · JavaScript · Node.js · Servicios REST',achievement:'Contribución frontend para desarrollar y poner al día procesos que se encontraban atrasados.'},
{role:'Ingeniero de Desarrollo',company:'GML Software',period:'Dic 2020 — May 2021',points:['Desarrollo de plataformas para firma de documentos y control de tiempos.','Participación en el ciclo completo de desarrollo.','Automatización de procesos y soluciones para más de 2.000 clientes.'],tech:'Laravel · Lumen · Vue.js · MySQL',achievement:'Construcción de soluciones y automatización de procesos para plataformas utilizadas por más de 2.000 clientes.'},
{role:'Analista Desarrollador Backend',company:'Locatel Colombia',period:'Nov 2019 — Nov 2020',points:['Desarrollo y mantenimiento de plataformas backend en producción.','Integración con VTEX para extracción y distribución de pedidos por sede.','Inventario visual, rutas y automatización mediante REST y SOAP.'],tech:'PHP · Laravel · Vue.js · Angular · MySQL · REST · SOAP',achievement:'Integraciones que procesaban entre 100 y 200 pedidos diarios.'},
{role:'Desarrollador Web',company:'Singularcom S.A.',period:'Abr 2018 — Oct 2019',points:['Aplicaciones para contabilidad e inventarios.','Nuevos requerimientos y reportes.','Mejoras de rendimiento en plataformas productivas.'],tech:'PHP · Laravel · CodeIgniter · AngularJS · MySQL',achievement:'Desarrollo de funcionalidades para facilitar procesos de contabilidad, facturación, inventarios, recepción y control de ingresos.'},
{role:'Técnico de Software',company:'RHS Alianza Homecare IPS',period:'Nov 2017 — Mar 2018',points:['Soporte y desarrollo de soluciones web.','Análisis de requerimientos.','Mantenimiento de plataformas y atención a usuarios.'],tech:'PHP · HTML5 · CSS · JavaScript',achievement:'Desarrollo de aplicaciones internas para pedidos del call center, reconstrucción del sistema de inventario y organización de archivos RIPS para la Superintendencia de Salud.'},
{role:'Consultor',company:'Everis S.A.S.',period:'Ago 2017 — Oct 2017',points:['Recolección y análisis de requerimientos.','Desarrollo de aplicaciones web.','Coordinación con equipos externos.'],tech:'PHP · JavaScript · MySQL',achievement:'Levantamiento y análisis de información para la definición de nuevos requerimientos.'},
{role:'Desarrollador PHP',company:'Grupo Konecta',period:'Ago 2016 — Abr 2017',points:['Desarrollo de plataformas web.','Soporte de sistemas en producción.','Reportes y gestión de versiones con Git.'],tech:'PHP · Yii · HTML5 · JavaScript · MySQL · Git',achievement:'Desarrollo y migración de aplicaciones para campañas de llamadas, apoyando el flujo de atención y la recolección de datos por parte de los asesores.'}];
const featuredProjects=[
{id:'citail',name:'Citail',category:'Gestión de reservas',context:'Plataforma multinegocio orientada inicialmente a IPS.',period:'2025',status:'Productivo',description:'Plataforma web orientada a la gestión de citas, agendas y reservas, diseñada para centralizar la administración de disponibilidad, clientes y procesos de atención.',participation:'Desarrollador full stack con responsabilidad completa sobre la arquitectura y la implementación.',architecture:'Arquitectura de cinco microservicios.',challenge:'Control de tiempos de citas por empleados y notificaciones mediante WebSockets.',outcome:'Control organizacional inmediato de los tiempos de las citas. Productivo en una entidad privada.',technologies:['Laravel','Angular','MySQL','Docker','WebSockets'],repositoryUrl:'',websiteUrl:'',image:'',colors:['#163e38','#0a1b19']},
{id:'vibook',name:'Vibook',category:'Comercio electrónico',context:'Plataforma administrable para la promoción de libros y redirección hacia comercios electrónicos externos.',period:'',status:'Productivo',description:'Plataforma de comercio electrónico creada para un escritor, enfocada en la promoción y venta de libros por internet mediante una experiencia sencilla y accesible.',participation:'Desarrollador full stack responsable de la implementación completa del backend y frontend.',architecture:'El panel permite configurar títulos, imágenes, banners, secciones, notificaciones y libros mostrados en el inicio. No gestiona pagos, pedidos ni inventario.',challenge:'Diseño e implementación del flujo funcional solicitado por el cliente, con una plataforma configurable desde el panel administrativo.',outcome:'Productivo.',technologies:['Vue.js','CodeIgniter','Bootstrap Dark'],repositoryUrl:'',websiteUrl:'https://vibook.com.co/',image:'./assets/vibook-cover.png',colors:['#16434a','#081a1d']},
{id:'fundacion-john',name:'Fundación John',category:'Impacto social',context:'Plataforma para comunicar actividades y facilitar la recepción de aportes.',period:'',status:'Pausado',description:'Plataforma web para publicar eventos y actividades de la fundación, además de facilitar la recepción y comunicación de donaciones y aportes.',participation:'Desarrollador full stack responsable de la integración completa de pagos.',architecture:'Integración de PayU con PSE.',challenge:'Implementación del flujo de aportes mediante la pasarela de pagos.',outcome:'El proyecto quedó pausado mientras la fundación completa los recursos y requisitos operativos necesarios para mantener su presencia digital y habilitar formalmente la recepción de aportes.',technologies:['Laravel','Vue.js','PayU','PSE'],repositoryUrl:'',websiteUrl:'',image:'',colors:['#503749','#1d1019']},
{id:'intrapitalito',name:'Intrapitalito',category:'Movilidad y gestión pública',context:'Plataforma interna para integrar procesos de movilidad, comparendos, facturación, cursos, transporte público, PQRS, documentos, patios y usuarios corporativos.',period:'',status:'En operación',description:'Plataforma para apoyar la gestión de movilidad y comparendos del Instituto de Tránsito y Transporte del municipio de Pitalito, Huila.',participation:'Líder técnico y desarrollador backend. Coordinación técnica de 3 desarrolladores frontend, 2 backend, 1 QA y 1 DevOps, todos profesionales independientes.',architecture:'Integración mediante RabbitMQ, NATS y HTTPS. Uso directo de S3, CloudWatch, DynamoDB, ElastiCache y Terraform.',challenge:'Comunicación e integración de múltiples procesos que se ejecutaban por separado dentro de la entidad.',outcome:'Producto interno en operación dentro de la entidad.',technologies:['NestJS','Angular','PostgreSQL','Redis','RabbitMQ','NATS','HTTPS','AWS','Terraform'],repositoryUrl:'',websiteUrl:'',image:'',colors:['#243f35','#0b1814']},
{id:'jam-with-jamie',name:'Jam with Jamie',category:'Gestión de eventos',context:'Plataforma para la operación de eventos de entretenimiento y educación musical infantil en Estados Unidos.',period:'',status:'Productivo',description:'Plataforma para gestionar eventos de entretenimiento y educación musical infantil en diferentes estados y ciudades de Estados Unidos.',participation:'Desarrollador full stack.',architecture:'Calendarios personalizados, pagos con Stripe, correos masivos y personalizados mediante Brevo y notificaciones en tiempo real con Reverb.',challenge:'Implementación de notificaciones para informar al administrador cuando una reserva era completada y facilitar la validación de flujos abandonados o inconsistentes.',outcome:'Productivo.',technologies:['CodeIgniter','Vue.js','MySQL','Reverb','Stripe','Brevo'],repositoryUrl:'',websiteUrl:'https://jamwithjamie.com',image:'./assets/jam-with-jamie-cover.png',colors:['#3f354f','#17121e']},
{id:'reposubasta',name:'Reposubasta',category:'Subastas en línea',context:'Plataforma de Puerto Rico para subastas de propiedades.',period:'',status:'Productivo',description:'Plataforma de Puerto Rico para participar en subastas y procesos de oferta sobre propiedades comerciales, residenciales y terrenos.',participation:'Desarrollador full stack enfocado en organización de bienes, ampliación de información, WebSockets y actualización de la integración con PayPal.',architecture:'Los detalles internos y la arquitectura permanecen confidenciales.',challenge:'Actualización de PayPal y notificación en tiempo real de la oferta más alta.',outcome:'Productivo.',technologies:['Laravel','Blade','WebSockets','PayPal'],repositoryUrl:'',websiteUrl:'https://reposubasta.com/es',image:'',colors:['#4b3526','#1c120c']}
];
const githubRepositories=[{name:'caicedo97.github.io',description:'Sitio web personal publicado mediante GitHub Pages.',language:'HTML',repositoryUrl:'https://github.com/caicedo97/caicedo97.github.io',websiteUrl:'https://caicedo97.github.io',featured:false}];
let lastProjectTrigger=null;
const projectsGrid=document.querySelector('#projects-grid'),githubGrid=document.querySelector('#github-repositories'),projectModal=document.querySelector('#project-modal'),modalPanel=projectModal.querySelector('.modal-panel'),modalContent=document.querySelector('#modal-content');
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const projectVisual=project=>project.image?`<img src="${escapeHtml(project.image)}" alt="Portada de ${escapeHtml(project.name)}" loading="lazy">`:`<div class="project-placeholder" role="img" aria-label="Portada conceptual de ${escapeHtml(project.name)}"><span class="placeholder-grid"></span><strong class="placeholder-mark">${escapeHtml(project.name.split(' ').map(word=>word[0]).join('').slice(0,2))}</strong><span class="placeholder-label">Project showcase</span></div>`;
const projectLinks=project=>`${project.repositoryUrl?`<a class="project-action" href="${escapeHtml(project.repositoryUrl)}" target="_blank" rel="noopener noreferrer" aria-label="Abrir repositorio de ${escapeHtml(project.name)} en una pestaña nueva">Repositorio ↗</a>`:''}${project.websiteUrl?`<a class="project-action" href="${escapeHtml(project.websiteUrl)}" target="_blank" rel="noopener noreferrer" aria-label="Abrir ${escapeHtml(project.name)} en una pestaña nueva">Ver proyecto ↗</a>`:''}`;
function renderFeaturedProjects(){projectsGrid.innerHTML=featuredProjects.map((project,index)=>`<article class="project reveal" style="--cover-a:${project.colors[0]};--cover-b:${project.colors[1]};--delay:${index*90}ms"><div class="project-cover">${projectVisual(project)}</div><div class="project-body"><div class="project-meta"><span class="project-category">${escapeHtml(project.category)}</span><span class="status-badge">${escapeHtml(project.status)}</span></div><h3>${escapeHtml(project.name)}</h3><p class="project-description">${escapeHtml(project.description)}</p><div class="project-tech">${project.technologies.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}</div><div class="project-actions"><button class="project-action primary" type="button" data-project="${project.id}" aria-label="Ver detalles de ${escapeHtml(project.name)}">Ver detalles</button>${projectLinks(project)}</div></div></article>`).join('')}
function renderGithubRepositories(){githubGrid.innerHTML=githubRepositories.map(repository=>`<article class="github-card"><div class="github-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 .8a11.5 11.5 0 0 0-3.6 22.4c.6.1.8-.3.8-.6v-2.2c-3.3.7-4-1.4-4-1.4-.5-1.4-1.3-1.8-1.3-1.8-1.1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1.1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-5.7 0-1.3.5-2.3 1.2-3.1-.1-.3-.5-1.6.1-3.1 0 0 1-.3 3.2 1.2A11 11 0 0 1 12 6.6c1 0 2 .1 2.9.4 2.2-1.5 3.2-1.2 3.2-1.2.6 1.5.2 2.8.1 3.1.8.8 1.2 1.8 1.2 3.1 0 4.4-2.8 5.4-5.5 5.7.4.4.8 1.1.8 2.2v2.7c0 .4.2.7.8.6A11.5 11.5 0 0 0 12 .8Z"/></svg></div><div class="github-content"><span>${escapeHtml(repository.language)}</span><h4>${escapeHtml(repository.name)}</h4><p>${escapeHtml(repository.description)}</p></div><div class="github-actions"><a class="project-action primary" href="${escapeHtml(repository.repositoryUrl)}" target="_blank" rel="noopener noreferrer" aria-label="Ver repositorio ${escapeHtml(repository.name)} en una pestaña nueva">Ver repositorio ↗</a>${repository.websiteUrl?`<a class="project-action" href="${escapeHtml(repository.websiteUrl)}" target="_blank" rel="noopener noreferrer" aria-label="Ver sitio de ${escapeHtml(repository.name)} en una pestaña nueva">Ver sitio ↗</a>`:''}</div></article>`).join('')}
function openProject(project,trigger){lastProjectTrigger=trigger;modalContent.innerHTML=`<div class="modal-cover" style="--cover-a:${project.colors[0]};--cover-b:${project.colors[1]}">${projectVisual(project)}</div><div class="modal-body"><div class="project-meta"><span class="project-category">${escapeHtml(project.category)}</span>${project.period?`<span class="status-badge">${escapeHtml(project.period)}</span>`:''}</div><h2 id="modal-title">${escapeHtml(project.name)}</h2><p class="modal-lead">${escapeHtml(project.description)}</p><div class="case-context"><h3>Contexto</h3><p>${escapeHtml(project.context)}</p></div><div class="modal-details"><div><h3>Mi participación</h3><p>${escapeHtml(project.participation)}</p></div><div><h3>Arquitectura e integraciones</h3><p>${escapeHtml(project.architecture)}</p></div><div><h3>Reto técnico</h3><p>${escapeHtml(project.challenge)}</p></div><div><h3>Resultado</h3><p>${escapeHtml(project.outcome)}</p></div><div><h3>Tecnologías</h3><div class="project-tech">${project.technologies.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}</div></div></div>${project.repositoryUrl||project.websiteUrl?`<div class="modal-actions">${projectLinks(project)}</div>`:''}</div>`;projectModal.hidden=false;document.body.classList.add('modal-open');modalPanel.focus()}
function closeProject(){if(projectModal.hidden)return;projectModal.classList.add('closing');setTimeout(()=>{projectModal.hidden=true;projectModal.classList.remove('closing');document.body.classList.remove('modal-open');lastProjectTrigger?.focus()},200)}
projectsGrid.addEventListener('click',event=>{const trigger=event.target.closest('[data-project]');if(trigger)openProject(featuredProjects.find(project=>project.id===trigger.dataset.project),trigger)});projectModal.addEventListener('click',event=>{if(event.target.closest('[data-close-modal]'))closeProject()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!projectModal.hidden)closeProject();if(event.key==='Tab'&&!projectModal.hidden){const focusable=[...projectModal.querySelectorAll('button,a[href]')];const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});
renderFeaturedProjects();renderGithubRepositories();
const projectObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){[...projectsGrid.children].forEach((card,index)=>{card.classList.remove('is-filtering');card.classList.add('reveal');card.style.setProperty('--delay',`${index*90}ms`);requestAnimationFrame(()=>card.classList.add('visible'))});projectObserver.disconnect()}}),{threshold:.12});projectObserver.observe(document.querySelector('#proyectos'));
document.querySelector('#specialties').innerHTML=specialties.map(([i,t,d])=>`<article class="card"><span class="icon" aria-hidden="true">${i}</span><h3>${t}</h3><p>${d}</p></article>`).join('');
document.querySelector('#work-practices').innerHTML=workPractices.map((practice,index)=>`<article><span aria-hidden="true">0${index+1}</span><h3>${escapeHtml(practice.name)}</h3><p>${escapeHtml(practice.description)}</p></article>`).join('');
document.querySelector('#profile-role').textContent=profile.role;
document.querySelector('#profile-name').textContent=profile.name;
document.querySelector('#profile-headline').innerHTML=profile.headline;
document.querySelector('#profile-summary').textContent=profile.summary;
document.querySelector('#profile-highlights').innerHTML=profile.highlights.map(item=>`<li>${escapeHtml(item)}</li>`).join('');
document.querySelector('#profile-skills').innerHTML=profile.featuredSkills.map((item,index)=>`<span style="--skill-delay:${index*65}ms">${escapeHtml(item)}</span>`).join('');
document.querySelector('#tech-groups').innerHTML=Object.entries(tech).map(([g,items])=>`<div class="tech-group"><h3>${g}</h3><div class="tags">${items.map(x=>`<span>${x}</span>`).join('')}</div></div>`).join('');
document.querySelector('#timeline').innerHTML=jobs.map((j,i)=>`<article class="job ${i>4?'extra':''}"><time>${j.period}</time><div class="job-body"><span class="company">${j.company}</span><h3>${j.role}</h3><ul>${j.points.map(p=>`<li>${p}</li>`).join('')}</ul>${j.achievement?`<p class="achievement">${j.achievement}</p>`:''}<p class="job-tech">${j.tech}</p></div></article>`).join('');
const more=document.querySelector('#more-experience'),timeline=document.querySelector('#timeline');more.addEventListener('click',()=>{const open=timeline.classList.toggle('expanded');more.textContent=open?'Ocultar trayectoria ↑':'Ver trayectoria completa ↓';more.setAttribute('aria-expanded',open)});
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.textContent=open?'×':'☰'});nav.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰'});
document.querySelector('#year').textContent=new Date().getFullYear();
// Visual behavior only: layered reveals and active navigation.
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const revealTargets=[...document.querySelectorAll('.section:not(.hero), .metrics article, .card, .tech-group, .education article, .github-card')];
revealTargets.forEach((element,index)=>{element.classList.add('reveal-on-scroll');element.style.setProperty('--reveal-delay',`${Math.min(index%4,3)*65}ms`)});
if(reducedMotion){revealTargets.forEach(element=>element.classList.add('is-visible'))}else{const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.09,rootMargin:'0px 0px -45px'});revealTargets.forEach(element=>revealObserver.observe(element))}
const header=document.querySelector('.nav');
const navLinks=[...document.querySelectorAll('.nav nav a[href^="#"]')];
const linkedSections=navLinks.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);
const topMarker=document.querySelector('#inicio');
const headerObserver=new IntersectionObserver(([entry])=>header.classList.toggle('scrolled',!entry.isIntersecting),{rootMargin:'-80px 0px 0px'});headerObserver.observe(topMarker);
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(link=>{const active=link.getAttribute('href')===`#${entry.target.id}`;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current')})}}),{rootMargin:'-35% 0px -55%'});linkedSections.forEach(section=>sectionObserver.observe(section));
